version: "3.7"

services:
  ankieta:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - ./config/pg/db.env
    volumes:
      - ./data/pg:/var/lib/postgresql/data
      - ./config/pg/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -d ankieta
      interval: 10s
      timeout: 45s
      retries: 10
