version: "3"
services:

  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      -  /home/nonroot/teamcity/pgdata:/var/lib/postgresql/data

  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - /home/nonroot/teamcity/data:/data/teamcity_server/datadir
      - /home/nonroot/teamcity/logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent:
    image: jetbrains/teamcity-agent
    privileged: true
    volumes:
      - /home/nonroot/teamcity/agent-conf:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=teamcity-server:8111
